### ISSUE TITLE
'path' argument is null

### ISSUE THREAD

**Issue by pavel-vorobiov** [chivaler/ATG-Toolkit#2]
After installing of the plugin and enabling both 'Attach Configuration Roots' and 'Attach ClassPath roots' got this exception:
```
Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.$$$reportNull$$$0(LocalFileSystemBase.java)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java)
	at org.idea.plugin.atg.util.AtgEnvironmentUtil.parseAtgHome(AtgEnvironmentUtil.java:54)
	at org.idea.plugin.atg.util.AtgEnvironmentUtil.addAtgDependenciesForAllModules(AtgEnvironmentUtil.java:288)
	at org.idea.plugin.atg.config.AtgToolkitSettingsUi.lambda$apply$0(AtgToolkitSettingsUi.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pavel-vorobiov** [comment]
ATG Toolkit v0.8

**Comment by KITSIgorPidgurskyi** [comment]
@pavel-vorobiov Thanks for the defect.
I've added better error handling when ATG_HOME root folder isn't set.
In the snapshot below error notifications are shown instead of stackTrace.
https://github.com/chivaler/ATG-Toolkit/releases/download/0.9.2/atg-toolkit-0.9.2.zip
Suppose, I will add later direct link to Path Variables to the Notification.

Regarding your problem - you need to have properly set "ATG_HOME" variable in "File | Settings | Appearance & Behavior | Path Variables" to use DependencyManagement functionality
Also you need to have set "ATG Module Name" property for your modules, how its described in https://github.com/chivaler/ATG-Toolkit/wiki/Dependency-management

**Comment by KITSIgorPidgurskyi** [comment]
@pavel-vorobiov Fix in release branch
